#Лабораторная работа №2

Температура вынутого из печи хлеба в течение 20 мин падает от 100°С до 60°С.
Температура воздуха равна 25°С. Через сколько времени от момента начала охлаждения
температура хлеба понизится до 30°С?
  * T(0) = 100;
  * T(20) = 60;
  * T = 30;
  * A = 25.

In [1]:
import numpy as np
import sys
import matplotlib.pyplot as plt

In [23]:
x0 = 0
T_0 = y0 = 100
a = 0
b = 100
T_20 = 60
A = 25
t = 20
T = 30
k = -np.log((T_20-A)/(T_0-A))/t
N = 128
eps = 0.0001
np.set_printoptions(suppress=True, threshold=sys.maxsize)

In [11]:
k

0.038107002602344835

In [7]:
def f(x, y):
    return -k*(y - A)

In [8]:
def calc_Runge_Kutta(f, y, x, h):
    k1 = h * f(x, y)
    k2 = h * f(x + h / 2, y + k1 / 2)
    k3 = h * f(x + h / 2, y + k2 / 2)
    k4 = h * f(x + h, y + k3)
    delta_y = (k1 + 2 * k2 + 2 * k3 + k4) / 6
    y = y + delta_y
    return y

In [21]:
def method_Runge_Kutta(f, y0, x0, a, b, N, eps):
    x = x0
    y = y0
    h = (b - a) / N
    i = 0
    table = [[0, 0, 0]]
    x_values = []  # Список для хранения значений x
    y_values = []  # Список для хранения значений y
    while x <= b:
        while np.abs(calc_Runge_Kutta(f, y, x, (b - a) / (2 * N)) - calc_Runge_Kutta(f, y, x, h)) / 15 > eps:
            N *= 2
            h = (b - a) / N
        y = calc_Runge_Kutta(f, y, x, h)

        if y.real >= T:
          i += 1
          x_values.append(x.real)  # Добавляем текущее значение x
          y_values.append(y.real)  # Добавляем текущее значение y
          table.append([i, x.real, y.real])
          x += h

        else:
          break

    return table, x_values, y_values

In [24]:
res, x_vals, y_vals = method_Runge_Kutta(f, y0, x0, a, b, N, eps)

In [25]:
# Вывод результата
res = np.array(res)
print("iter\t   x\t\t   y")
print(res)

Выходные данные были обрезаны до нескольких последних строк (5000).
 [88146.            67.2492981     30.78223255]
 [88147.            67.25006104    30.78206444]
 [88148.            67.25082397    30.78189634]
 [88149.            67.25158691    30.78172825]
 [88150.            67.25234985    30.78156016]
 [88151.            67.25311279    30.78139207]
 [88152.            67.25387573    30.78122399]
 [88153.            67.25463867    30.78105591]
 [88154.            67.25540161    30.78088784]
 [88155.            67.25616455    30.78071977]
 [88156.            67.25692749    30.78055171]
 [88157.            67.25769043    30.78038365]
 [88158.            67.25845337    30.7802156 ]
 [88159.            67.25921631    30.78004755]
 [88160.            67.25997925    30.77987951]
 [88161.            67.26074219    30.77971147]
 [88162.            67.26150513    30.77954344]
 [88163.            67.26226807    30.77937541]
 [88164.            67.26303101    30.77920738]
 [88165.            